In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# import plotly.express as px
# from plotly import graph_objects as go

import matplotlib
import sklearn
# import plotly

from IPython.display import display

print("package版本信息：")
print("numpy:      ", np.__version__)
print("pandas:     ", pd.__version__)
print("matplotlib: ", matplotlib.__version__)
print("sklearn:    ", sklearn.__version__)
print("seaborn:    ", sns.__version__)
# print("plotly:     ", plotly.__version__)

package版本信息：
numpy:       1.23.3
pandas:      1.4.4
matplotlib:  3.5.3
sklearn:     1.1.2
seaborn:     0.12.1


# 介绍

整理 `sklearn.ensemble` 模块里提供的集成学习模型，该模块里主要分为如下几类集成模型：
+ Bagging
+ Boosting
+ 结合策略
+ 其他

## 数据集

使用的数据集如下：

In [3]:
from sklearn.model_selection import train_test_split

### 回归问题

In [4]:
from sklearn.datasets import fetch_california_housing

In [5]:
housing_data = fetch_california_housing(as_frame=True)

In [6]:
print(housing_data.keys())

dict_keys(['data', 'target', 'frame', 'target_names', 'feature_names', 'DESCR'])


In [7]:
print('feature_names: ', housing_data.feature_names)
print('target_names: ', housing_data.target_names)

feature_names:  ['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup', 'Latitude', 'Longitude']
target_names:  ['MedHouseVal']


In [8]:
print(housing_data.data.shape)

(20640, 8)


In [9]:
housing_data.frame.head(5)

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  MedHouseVal  
0    -122.23        4.526  
1    -122.22        3.585  
2    -122.24        3.521  
3    -122.25        3.413  
4    -122.25        3.422

In [14]:
print(housing_data.DESCR)

.. _california_housing_dataset:

California Housing dataset
--------------------------

**Data Set Characteristics:**

    :Number of Instances: 20640

    :Number of Attributes: 8 numeric, predictive attributes and the target

    :Attribute Information:
        - MedInc        median income in block group
        - HouseAge      median house age in block group
        - AveRooms      average number of rooms per household
        - AveBedrms     average number of bedrooms per household
        - Population    block group population
        - AveOccup      average number of household members
        - Latitude      block group latitude
        - Longitude     block group longitude

    :Missing Attribute Values: None

This dataset was obtained from the StatLib repository.
https://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html

The target variable is the median house value for California districts,
expressed in hundreds of thousands of dollars ($100,000).

This dataset was derived

+ 划分训练&验证集和测试集

In [10]:
housing_X_train, housing_X_test, housing_y_train, housing_y_test = train_test_split(housing_data.data, housing_data.target, test_size=0.2, random_state=32)

In [11]:
housing_X_train.head(5)

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
1032   3.1250      23.0  6.375796   1.242038       369.0  2.350318     38.51   
10807  4.4211      35.0  5.305970   1.027363      1473.0  3.664179     33.65   
87     0.7600      10.0  2.651515   1.054545       546.0  1.654545     37.81   
4395   2.6178      52.0  3.304290   1.036193      2328.0  3.120643     34.08   
19053  3.2937      33.0  5.317647   1.067647       824.0  2.423529     38.16   

       Longitude  
1032     -120.80  
10807    -117.93  
87       -122.27  
4395     -118.28  
19053    -121.69

In [12]:
housing_y_train.head()

1032     0.964
10807    2.152
87       1.625
4395     2.031
19053    0.964
Name: MedHouseVal, dtype: float64

### 分类问题

下面是一个二分类的数据集。

In [31]:
from sklearn.datasets import load_breast_cancer

In [32]:
cancer_data = load_breast_cancer(as_frame=True)

In [33]:
print(cancer_data.keys())

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [34]:
print('feature_names: ', cancer_data.feature_names)
print('target_names: ',cancer_data.target_names)

feature_names:  ['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']
target_names:  ['malignant' 'benign']


In [35]:
print(cancer_data.data.shape)

(569, 30)


In [36]:
cancer_data.frame.head(5)

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  target  
0          0.4601                  0.11890       0  
1          0.2750                  0.08902       0  
2          0.3613                  0.08758       0  
3          0.6638                  0.17300       0  
4          0.2364                  0.07678       0  

[5 rows x 31 columns]

In [24]:
print(cancer_data.DESCR)

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        worst/largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 0 is Mean Radi

+ 划分训练&验证集和测试集

In [37]:
cancer_X_train, cancer_X_test, cancer_y_train, cancer_y_test = train_test_split(cancer_data.data, cancer_data.target, test_size=0.2, random_state=32)

In [38]:
cancer_X_train.head(5)

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
408        17.99         20.66          117.80      991.7          0.10360   
298        14.26         18.17           91.22      633.1          0.06576   
282        19.40         18.18          127.20     1145.0          0.10370   
199        14.45         20.22           94.49      642.7          0.09872   
307         9.00         14.40           56.36      246.3          0.07005   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
408           0.13040        0.120100             0.088240         0.1992   
298           0.05220        0.024750             0.013740         0.1635   
282           0.14420        0.162600             0.094640         0.1893   
199           0.12060        0.118000             0.059800         0.1950   
307           0.03116        0.003681             0.003472         0.1788   

     mean fractal dimension  ...  worst radius  worst texture  \
408                 0.06069  ...        21.080          25.41   
298                 0.05586  ...        16.220          25.26   
282                 0.05892  ...        23.790          28.65   
199                 0.06466  ...        18.330          30.12   
307                 0.06833  ...         9.699          20.07   

     worst perimeter  worst area  worst smoothness  worst compactness  \
408            138.1      1349.0           0.14820            0.37350   
298            105.8       819.7           0.09445            0.21670   
282            152.4      1628.0           0.15180            0.37490   
199            117.9      1044.0           0.15520            0.40560   
307             60.9       285.5           0.09861            0.05232   

     worst concavity  worst concave points  worst symmetry  \
408          0.33010               0.19740          0.3060   
298          0.15650               0.07530          0.2636   
282          0.43160               0.22520          0.3590   
199          0.49670               0.18380          0.4753   
307          0.01472               0.01389          0.2991   

     worst fractal dimension  
408                  0.08503  
298                  0.07676  
282                  0.07787  
199                  0.10130  
307                  0.07804  

[5 rows x 30 columns]

---
# Bagging

提供了并行集成相关的模型。

## 基础bagging模型

```python
# 回归问题
BaggingRegressor(
    estimator=None, n_estimators=10, *, 
    max_samples=1.0, max_features=1.0, 
    bootstrap=True, bootstrap_features=False, oob_score=False, 
    warm_start=False, n_jobs=None, random_state=None, verbose=0
)

# 分类问题
BaggingClassifier(
    estimator=None, n_estimators=10, *, 
    max_samples=1.0, max_features=1.0, 
    bootstrap=True, bootstrap_features=False, oob_score=False, 
    warm_start=False, n_jobs=None, random_state=None, verbose=0
)
```

## Random Forests

sklearn提供的API如下：
```python
# 回归问题
RandomForestRegressor(
    n_estimators=100, *, 
    criterion='squared_error', 
    max_depth=None, min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, 
    max_features=1.0, max_leaf_nodes=None, min_impurity_decrease=0.0, 
    bootstrap=True, oob_score=False, n_jobs=None, random_state=None, 
    verbose=0, warm_start=False, ccp_alpha=0.0, max_samples=None, monotonic_cst=None
)

# 分类问题
RandomForestClassifier(
    n_estimators=100, *, 
    criterion='gini', 
    max_depth=None, min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, 
    max_features='sqrt', max_leaf_nodes=None, min_impurity_decrease=0.0, 
    bootstrap=True, oob_score=False, n_jobs=None, random_state=None, 
    verbose=0, warm_start=False, 
    class_weight=None,   # 独有参数
    ccp_alpha=0.0, max_samples=None, monotonic_cst=None
)
```

此外，sklearn还提供了一个基于随机森林的无监督密度估计方法。
```python
RandomTreesEmbedding(
    n_estimators=100, *, 
    max_depth=5, min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, 
    max_leaf_nodes=None, min_impurity_decrease=0.0, sparse_output=True, 
    n_jobs=None, random_state=None, verbose=0, warm_start=False
)
```

## Extremely Randomized Trees

---
# Boosting

提供了串行集成相关的模型。

## AdaBoost

sklearn提供的API如下：
```python
# 回归问题
AdaBoostRegressor(estimator=None, *, n_estimators=50, learning_rate=1.0, loss='linear', random_state=None)

# 分类问题
AdaBoostClassifier(estimator=None, *, n_estimators=50, learning_rate=1.0, algorithm='SAMME.R', random_state=None)
```

---
## GBDT - KEY

sklearn提供了两个版本的GBDT实现，普通版本和快速版本。

### 普通版本
```python
# 回归树 API
GradientBoostingRegressor(*, 
    loss='squared_error',
    learning_rate=0.1, n_estimators=100, subsample=1.0, criterion='friedman_mse', 
    min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_depth=3, min_impurity_decrease=0.0,
    init=None, random_state=None, max_features=None, 
    alpha=0.9,   # 回归树独有
    verbose=0, max_leaf_nodes=None, warm_start=False, validation_fraction=0.1,
    n_iter_no_change=None, tol=0.0001, ccp_alpha=0.0
)

# 分类树 API
GradientBoostingClassifier(*,
    loss='log_loss',
    learning_rate=0.1, n_estimators=100, subsample=1.0, criterion='friedman_mse', 
    min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_depth=3, min_impurity_decrease=0.0,
    init=None, random_state=None, max_features=None, 
    verbose=0, max_leaf_nodes=None, warm_start=False, validation_fraction=0.1, 
    n_iter_no_change=None, tol=0.0001, ccp_alpha=0.0
)
```

对比可以看出，两者的参数里，除了 `loss` 不一样，几乎都一致，除了回归树多了一个`alpha`参数，因此下面就一起介绍了。

#### 参数

GBDT普通版本的参数可以分为如下 4 类：

+ 训练过程

| 参数                                   | 含义                     | 影响力 | 说明                                    |
| -------------------------------------- | ------------------------ | ------ | --------------------------------------- |
| loss                                   | 损失函数                 | ⭐⭐⭐    | 可选值见下面说明                        |
| <font color="red">n_estimators</font>  | 基函数个数               | ⭐⭐⭐⭐⭐  | int，默认100                            |
| <font color="red">learning_rate</font> | 学习率                   | ⭐⭐⭐⭐⭐  | float，默认0.1                          |
| <font color="red">max_features</font>  | 基函数训练时使用的特征数 | ⭐⭐⭐⭐⭐  | 默认None表示使用全部。有多种方式配置。  |
| subsample                              | 基函数训练时的采样比例   | ⭐⭐⭐    | float，必须在 $(0.0,1.0])$之间，默认1.0 |
| init                                   | 初始值设置               | ⭐⭐      | 默认None                                |
| random_state                           | 随机数状态               | ⭐      | 默认None                                |
| alpha                                  |                          | ⭐      |                                         |


+ 基函数参数

| 参数                     | 含义                           | 影响力 | 说明                                            |
| ------------------------ | ------------------------------ | ------ | ----------------------------------------------- |
| criterion                | CART分裂时的准则               | ⭐⭐     | 可选值为`friedman_mse`（默认），`squared_error` |
| min_samples_split        | 节点分裂时需要包含的最小样本数 | ⭐⭐     | int表示个数（默认2），float表示比例             |
| min_samples_leaf         | 叶子节点的最小样本数           | ⭐⭐     | int表示个数，float表示比例                      |
| max_depth                | 树的最大深度                   | ⭐⭐     | int，默认3                                      |
| min_impurity_decrease    | 节点分裂时的最小不纯度增益     | ⭐⭐     | float，默认0.                                   |
| max_leaf_nodes           | 叶子结点的最大个数             | ⭐⭐     | int，默认None，表示无限制                       |
| min_weight_fraction_leaf |                                |        |                                                 |


+ 提前停止

| 参数                | 含义                                                   | 说明                              |
| ------------------- | ------------------------------------------------------ | --------------------------------- |
| validation_fraction | 用于计算提前停止的验证集比例                           | float，默认0.1                    |
| n_iter_no_change    | 提前停止的轮数，表示多少轮验证集无变化之后，就提前停止 | int，默认None，表示不启用提前停止 |
| tol                 | 提前停止判断的loss变化值                               | float，默认1e-4                   |

+ 其他

| 参数       | 含义 | 说明 |
| ---------- | ---- | ---- |
| verbose    |      |      |
| ccp_alpha  |      |      |
| warm_start |      |      |


#### 属性和方法

### 快速版本
```python
# 回归树 API
HistGradientBoostingRegressor(
    loss='squared_error', 
    *, quantile=None, 
    learning_rate=0.1, max_iter=100, max_leaf_nodes=31, max_depth=None, 
    min_samples_leaf=20, l2_regularization=0.0, max_features=1.0, max_bins=255,
    categorical_features='warn', monotonic_cst=None, interaction_cst=None, warm_start=False, 
    early_stopping='auto', scoring='loss', validation_fraction=0.1, 
    n_iter_no_change=10, tol=1e-07, verbose=0, random_state=None
)

# 分类树 API
HistGradientBoostingClassifier(
    loss='log_loss', 
    *, 
    learning_rate=0.1, max_iter=100, max_leaf_nodes=31, max_depth=None, 
    min_samples_leaf=20, l2_regularization=0.0, max_features=1.0, max_bins=255, 
    categorical_features='warn', monotonic_cst=None, interaction_cst=None, warm_start=False, 
    early_stopping='auto', scoring='loss', validation_fraction=0.1, 
    n_iter_no_change=10, tol=1e-07, verbose=0, random_state=None, 
    class_weight=None  # 分类树独有
)
```

对比可以看出，快速版本的回归和分类API参数差异也不大。

但是快速版本相比普通版本，提供了一些其他的支持。

#### 参数

快速版本特有的参数如下：

| 参数                 | 含义                                   | 影响力 | 说明         |
| -------------------- | -------------------------------------- | ------ | ------------ |
| max_iter             | 最大迭代次数，相当于`n_estimators`参数 |        | int，默认100 |
| l2_regularization    | L2正则项                               |        |              |
| max_bins             | 最大分箱数                             |        |              |
| categorical_features | 处理分类特征                           |        |              |
| monotonic_cst        |                                        |        |              |
| interaction_cst      |                                        |        |              |
| early_stopping       | 提前停止策略                           |        |              |
| scoring              | 提前停止的评价指标                     |        |              |
| quantile             | `loss='quantile'`时使用                |        |              |

#### 属性和方法

### 损失函数

sklearn里GBDT支持的损失函数如下.

#### 回归问题
`GradientBoostingRegressor`
+ squared_error，默认值
+ absolute_error
+ quantile
+ huber

`HistGradientBoostingRegressor`
+ squared_error
+ absolute_error
+ quantile
+ gamma
+ poisson

各损失函数详情如下：

+ **squared_error——平方误差**

$$
L = \sum{(y_i - H(x_i))^2}
$$

+ **absolute_error——绝对误差**

$$
L = \sum{|y_i - H(x_i)|}
$$


+ **quantile**

$$
L = \sum{l(y_i,H(x_i))}
$$

其中
$$
l = \begin{split} 
\begin{cases}
    \alpha (y_i - H(x_i)), & y_i - H(x_i) > 0 \\
    0,    & y_i - H(x_i) = 0 \\
    (1-\alpha) (y_i - H(x_i)), & y_i - H(x_i) < 0
\end{cases}\end{split}, \space \space \alpha \in (0, 1)
$$


+ **huber——合页误差**

$$
L = \sum{l(y_i,H(x_i))}
$$

其中
$$
l = \begin{split} 
\begin{cases}\frac{1}{2}(y_i - H(x_i))^2, & |y_i - H(x_i)|\leq\alpha \\
\alpha(|y_i - H(x_i)|-\frac{\alpha}{2}),& |y_i - H(x_i)|>\alpha \end{cases}\end{split}, \space \space \alpha \in (0, 1)
$$

其中$\alpha$是需要我们自己设置的超参数，由参数`alpha`控制。在huber损失中，alpha是阈值，在quantile损失中，alpha用于辅助计算损失函数的输出结果，默认为0.9

#### 分类问题
`GradientBoostingClassifier`
+ log_loss
+ exponential

`HistGradientBoostingClassifier`
+ log_loss, 只支持这一种


对任意样本$i$而言，$y_i$为真实标签，$\hat{y_i}$为预测标签，$H(x_i)$为集成算法输出结果，$p(x_i)$为基于$H(x_i)$和sigmoid/softmax函数计算的概率值。
那么各损失函数详情如下：

+ **log_loss——对数几率**，也叫交叉熵损失

**二分类交叉熵损失**
$$
L = -\left( y\log p(x) + (1 - y)\log(1 - p(x)) \right)
$$
注意，log当中输入的一定是概率值。对于逻辑回归来说，概率就是算法的输出，因此我们可以认为逻辑回归中$p = H(x)$，但对于GBDT来说，$p(x_i) = Sigmoid(H(x_i))$，这一点一定要注意。


**多分类交叉熵损失**，总共有K个类别

$$
L = -\sum_{k=1}^Ky^*_k\log(P^k(x))
$$

其中，$P^k(x)$是概率值，对于多分类GBDT来说，$p^k(x) = Softmax(H^k(x))$，$y^*$是由真实标签转化后的向量。

+ **exponential——指数损失**

**二分类指数损失**
$$
L = e^{-yH(x)}
$$

**多分类指数损失**，总共有K个类别
$$
\begin{aligned}
L &=exp \left( -\frac{1}{K}\boldsymbol{y^* · H^*(x)} \right) = exp \left( -\frac{1}{K}(y^1H^1(x)+y^2H^2(x) \ + \  ... + y^kH^k(x)) \right)
\end{aligned}
$$

需要注意，指数损失中的$y^*$与交叉熵损失中的$y^*$不是同样的向量。

### 使用

#### 回归

In [27]:
from sklearn.ensemble import GradientBoostingRegressor, HistGradientBoostingRegressor

#### 分类

In [26]:
from sklearn.ensemble import GradientBoostingClassifier, HistGradientBoostingClassifier

### 提前停止

### 袋外估计

---
# 结合策略

## Voting

sklearn提供的API如下：

```python
# 回归问题
VotingRegressor(
    estimators, *, 
    weights=None, n_jobs=None, verbose=False
)

# 分类问题
VotingClassifier(
    estimators, *, 
    voting='hard', weights=None, n_jobs=None, flatten_transform=True, verbose=False
)
```

### 回归问题

In [15]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.ensemble import VotingRegressor

In [16]:
lr = LinearRegression(fit_intercept=True)

In [17]:
dtr = DecisionTreeRegressor(max_depth=5)

In [18]:
svr = SVR(kernel='rbf')

In [19]:
voting_reg = VotingRegressor(estimators=[('lr', lr), ('dtr', dtr), ('svr', svr)])

In [20]:
voting_reg.estimators

[('lr', LinearRegression()),
 ('dtr', DecisionTreeRegressor(max_depth=5)),
 ('svr', SVR())]

In [21]:
voting_reg.named_estimators

{'lr': LinearRegression(),
 'dtr': DecisionTreeRegressor(max_depth=5),
 'svr': SVR()}

In [22]:
voting_reg.fit(housing_X_train, housing_y_train)

VotingRegressor(estimators=[('lr', LinearRegression()),
                            ('dtr', DecisionTreeRegressor(max_depth=5)),
                            ('svr', SVR())])

In [23]:
voting_reg.score(housing_X_train, housing_y_train)

0.572889667817913

### 分类问题

In [24]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier

In [25]:
logis = LogisticRegression()

In [26]:
dtc = DecisionTreeClassifier(max_depth=5)

In [52]:
svc_hard = SVC(kernel='rbf')
svc_soft = SVC(kernel='rbf', probability=True)

+ **硬投票**方式

In [53]:
voting_clf = VotingClassifier(estimators=[('logis', logis), ('dtc', dtc), ('svc', svc_hard)], voting='hard')

In [54]:
voting_clf.estimators

[('logis', LogisticRegression()),
 ('dtc', DecisionTreeClassifier(max_depth=5)),
 ('svc', SVC())]

In [55]:
voting_clf.named_estimators

{'logis': LogisticRegression(),
 'dtc': DecisionTreeClassifier(max_depth=5),
 'svc': SVC()}

In [56]:
voting_clf.fit(cancer_X_train, cancer_y_train)

C:\Users\Drivi\miniconda3\envs\data-analysis\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


VotingClassifier(estimators=[('logis', LogisticRegression()),
                             ('dtc', DecisionTreeClassifier(max_depth=5)),
                             ('svc', SVC())])

In [57]:
voting_clf.score(cancer_X_train, cancer_y_train)

0.9692307692307692

In [61]:
voting_clf.get_feature_names_out()

array(['votingclassifier_logis', 'votingclassifier_dtc',
       'votingclassifier_svc'], dtype=object)

In [74]:
cancer_y_pred = voting_clf.predict(cancer_X_train)
print(cancer_y_pred.shape)

(455,)


In [75]:
cancer_y_pred[:5]

array([0, 1, 0, 0, 1])

查看每个估计器的结果，硬投票下，每个估计器是直接给出分类结果。

In [72]:
t1 = voting_clf.transform(cancer_X_train)
print(t1.shape)

(455, 3)


In [73]:
t1[:5]

array([[0, 0, 0],
       [1, 1, 1],
       [0, 0, 0],
       [0, 0, 0],
       [1, 1, 1]], dtype=int64)

+ **软投票**的方式

In [58]:
voting_clf_soft = VotingClassifier(estimators=[('logis', logis), ('dtc', dtc), ('svc', svc_soft)], voting='soft')

In [59]:
voting_clf_soft.fit(cancer_X_train, cancer_y_train)

C:\Users\Drivi\miniconda3\envs\data-analysis\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


VotingClassifier(estimators=[('logis', LogisticRegression()),
                             ('dtc', DecisionTreeClassifier(max_depth=5)),
                             ('svc', SVC(probability=True))],
                 voting='soft')

In [60]:
voting_clf_soft.score(cancer_X_train, cancer_y_train)

0.9758241758241758

In [84]:
cancer_y_pred_soft = voting_clf_soft.predict(cancer_X_train)

In [85]:
cancer_y_pred_soft[:5]

array([0, 1, 0, 0, 1])

In [86]:
cancer_y_pred_prob = voting_clf_soft.predict_proba(cancer_X_train)

In [87]:
cancer_y_pred_prob[:5]

array([[9.99390992e-01, 6.09008273e-04],
       [2.09467514e-01, 7.90532486e-01],
       [9.99877726e-01, 1.22274476e-04],
       [9.77141433e-01, 2.28585672e-02],
       [3.80766551e-03, 9.96192334e-01]])

查看每个估计器的结果，软投票下，**6列是因为每个估计器分别给出正负两类各自的概率**。

In [96]:
t2 = voting_clf_soft.transform(cancer_X_train)
t2.shape

(455, 6)

In [83]:
t2[:5]

array([[9.99873367e-01, 1.26632846e-04, 1.00000000e+00, 0.00000000e+00,
        9.98299608e-01, 1.70039197e-03],
       [2.35197482e-01, 7.64802518e-01, 0.00000000e+00, 1.00000000e+00,
        3.93205060e-01, 6.06794940e-01],
       [9.99999928e-01, 7.19479381e-08, 1.00000000e+00, 0.00000000e+00,
        9.99633249e-01, 3.66751481e-04],
       [9.90907401e-01, 9.09259927e-03, 1.00000000e+00, 0.00000000e+00,
        9.40516898e-01, 5.94831025e-02],
       [2.20613146e-04, 9.99779387e-01, 0.00000000e+00, 1.00000000e+00,
        1.12023834e-02, 9.88797617e-01]])

正类的概率均值

In [94]:
t2[:5, [0,2,4]].mean(axis=1)

array([0.99939099, 0.20946751, 0.99987773, 0.97714143, 0.00380767])

负类的概率均值

In [95]:
t2[:5, [1,3,5]].mean(axis=1)

array([6.09008273e-04, 7.90532486e-01, 1.22274476e-04, 2.28585672e-02,
       9.96192334e-01])

---
## Stacking - KEY

有关Stacking的介绍，可以参考如下的几篇博客：
1. [模型融合方法概述](https://zhuanlan.zhihu.com/p/25836678)
2. [Kaggle机器学习之模型融合（stacking）心得](https://zhuanlan.zhihu.com/p/26890738)
3. [Introduction to Ensembling/Stacking in Python](https://www.kaggle.com/arthurtok/introduction-to-ensembling-stacking-in-python/notebook#Second-Level-Predictions-from-the-First-level-Output)

实现类详见`Stacking.py`文件。

sklearn提供的API如下：
```python
# 回归问题
StackingRegressor(
    estimators, 
    final_estimator=None, *, 
    cv=None, n_jobs=None, passthrough=False, verbose=0
)

# 分类问题
StackingClassifier(
    estimators, 
    final_estimator=None, *, 
    cv=None, stack_method='auto', n_jobs=None, passthrough=False, verbose=0
)
```

参数：
+ `estimators`: list of (str, estimator)
+ `final_estimator`: 元估计器
+ `cv`: 交叉验证的策略，这个参数要特别注意，可选值如下：
    + `None`，使用默认的5折交叉验证
    + 整数，指定交叉验证折数
    + 可以执行cross-validation的generator
    + 分割数据集的可迭代对象
    + `prefit`: <font color='red'>这个取值要特别注意，此时表示所有的一级估计器都是训练好的，元估计器不会使用交叉验证策略，而是使用一级估计器在所有数据上的输出</font>，此时会有数据泄露的情况，非常容易出现过拟合的情况。
+ `stack_method`: 融合策略，可选值为`{‘auto’, ‘predict_proba’, ‘decision_function’, ‘predict’}`
    + `auto`下会对每个估计器依次尝试`predict_proba`, `decision_function`, `predict` 方法
    + 其他选项则是自己指定使用的估计器方法
+ `passthrough`: 默认`False`，表示只有一级估计器的输出会被输入到元估计器中，`True`表示则会和原始数据一起输入元估计器中。

这里需要注意的是，Sklearn里实现的Stacking：
+ 在`cv`取值不是`prefit`的情况下，<font color='red'>会**对每个一级学习器**使用传入的**整个数据集**训练一次模型参数（**不是超参数**），然后使用交叉验证的方式得到每个一级学习器的OOB预测（内部调用的是`cross_val_predict()`方法）</font>。这一意味着，<font color='red'>传入的一级学习器所使用的最优超参数需要实现我们自己实现执行一次GridSearch+CV的搜索</font>，但是这个过程会出现数据泄露的情况，导致后续使用Stacking集成时极易出现过拟合的情况。
+  如果`cv='prefit'`，此时不会对一级学习器进行训练，也不会使用交叉验证的方式获取OOB预测，而是直接使用每个一级学习器在传入的数据集上的预测结果。

### 回归问题

### 分类问题

----
# 其他

## IsolationForest
孤立森林异常检测算法。

```python
IsolationForest(
    *, n_estimators=100, 
    max_samples='auto', contamination='auto', 
    max_features=1.0, bootstrap=False, 
    n_jobs=None, random_state=None, verbose=0, warm_start=False
)
```