In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [24]:
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import mean_squared_error as MSE

from sklearn.ensemble import RandomForestRegressor as RFR
from sklearn.linear_model import LinearRegression

import xgboost as xgb
from xgboost import XGBRegressor as XGBR

In [3]:
boston = load_boston()

In [4]:
boston.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])

In [5]:
boston.feature_names

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [8]:
boston.data.shape

(506, 13)

In [9]:
boston.filename

'/Users/danielzhang/anaconda3/lib/python3.6/site-packages/sklearn/datasets/data/boston_house_prices.csv'

In [10]:
X = boston.data
y = boston.target

In [11]:
Xtrain,Xtest,ytrain,ytest = train_test_split(X,y, test_size=0.3, random_state=29)

In [15]:
xgbr = XGBR(n_estimators=100)
xgbr.fit(Xtrain,ytrain)

In [17]:
# 这里默认返回的是R^2，不是MSE，可使用shift + tab查看签名
xgbr.score(Xtest,ytest)

0.8602355309236762

In [21]:
ytest.mean()

22.650000000000002

In [22]:
# MSE占到了均值的接近50%，效果不太好
MSE(ytest, xgbr.predict(Xtest))

11.135163981742757

In [23]:
xgbr.feature_importances_

array([0.04097971, 0.00196055, 0.01399265, 0.0260286 , 0.02934796,
       0.22701843, 0.00805854, 0.04400521, 0.01526619, 0.01207243,
       0.03462191, 0.01319523, 0.5334527 ], dtype=float32)

交叉验证效果

In [25]:
xgbr = XGBR(n_estimators=100)
cross_val_score(xgbr,X,y,cv=5)

[09:22:22] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[09:22:22] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[09:22:22] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[09:22:22] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[09:22:22] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


array([0.77955736, 0.85656904, 0.79106707, 0.57326677, 0.41285553])

In [29]:
# 查看sklearn中已有的指标
import sklearn
sorted(sklearn.metrics.SCORERS.keys())

['accuracy',
 'adjusted_mutual_info_score',
 'adjusted_rand_score',
 'average_precision',
 'balanced_accuracy',
 'completeness_score',
 'explained_variance',
 'f1',
 'f1_macro',
 'f1_micro',
 'f1_samples',
 'f1_weighted',
 'fowlkes_mallows_score',
 'homogeneity_score',
 'jaccard',
 'jaccard_macro',
 'jaccard_micro',
 'jaccard_samples',
 'jaccard_weighted',
 'max_error',
 'mutual_info_score',
 'neg_brier_score',
 'neg_log_loss',
 'neg_mean_absolute_error',
 'neg_mean_gamma_deviance',
 'neg_mean_poisson_deviance',
 'neg_mean_squared_error',
 'neg_mean_squared_log_error',
 'neg_median_absolute_error',
 'neg_root_mean_squared_error',
 'normalized_mutual_info_score',
 'precision',
 'precision_macro',
 'precision_micro',
 'precision_samples',
 'precision_weighted',
 'r2',
 'recall',
 'recall_macro',
 'recall_micro',
 'recall_samples',
 'recall_weighted',
 'roc_auc',
 'roc_auc_ovo',
 'roc_auc_ovo_weighted',
 'roc_auc_ovr',
 'roc_auc_ovr_weighted',
 'v_measure_score']

In [30]:
# 使用其他指标
cross_val_score(xgbr,X,y,cv=5,scoring='neg_mean_squared_error')

[09:24:33] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[09:24:33] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[09:24:33] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[09:24:33] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[09:24:33] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


array([ -7.61302966, -13.05748854, -16.73285435, -37.42956222,
       -15.6111833 ])

使用随机森林和线性回归作对比